# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Python vs R (dev)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 9 * * 1,3,5"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }})

    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, python-version: 3.8, r-version: release}
          - {os: windows-latest, python-version: 3.8, r-version: release}
          - {os: macOS-latest, python-version: 3.8, r-version: release}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}
    - name: Install Python pkg DoubleML (dev)
      run: |
        python -m pip install --upgrade pip
        cd doubleml-for-py
        pip install --editable .
        pip install pytest rpy2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.config.r }}
    - name: Query R pkg dependencies (taken from released!)
      run: |
        install.packages('remotes')
        saveRDS(remotes::package_deps("DoubleML", dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}
    - name: Cache R packages
      if: runner.os != 'Windows'
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-release-pkg-test-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-release-pkg-test
    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
        rm -rf /home/runner/work/_temp/Library
        mkdir /home/runner/work/_temp/Library
        sudo apt-get install -y zlib1g-dev libicu-dev pandoc make libcurl4-openssl-dev libssl-dev
    - name: Install R pkg DoubleML (dev)
      run: |
        install.packages('remotes')
        remotes::install_github("DoubleML/doubleml-for-r", dependencies = TRUE)
        remotes::install_cran("rcmdcheck")
      shell: Rscript {0}

    - name: Test with pytest
      run: |
        pytest
