# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Python vs R (dev)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1,3,5"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.config.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    name: ${{ matrix.config.os }} (${{ matrix.config.python-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, python-version: 3.8, r-version: release}
          - {os: windows-latest, python-version: 3.8, r-version: release}
          - {os: macOS-latest, python-version: 3.8, r-version: release}

    steps:
    - uses: actions/checkout@v3
      with:
        path: doubleml-py-vs-r
    - uses: actions/checkout@v3
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.config.python-version }}
    - name: Install Python pkg DoubleML (dev)
      run: |
        cd doubleml-py-vs-r
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip uninstall -y DoubleML
        cd ..
        cd doubleml-for-py
        pip install --editable .

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.config.r }}
    - name: Query R pkg dependencies (taken from released!)
      run: |
        install.packages('remotes')
        saveRDS(remotes::package_deps("DoubleML", dependencies = TRUE), "doubleml-py-vs-r/.github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), "doubleml-py-vs-r/.github/R-version")
      shell: Rscript {0}
    - name: Cache R packages
      if: runner.os != 'Windows'
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('doubleml-py-vs-r/.github/R-version') }}-dev-pkg-test-${{ hashFiles('doubleml-py-vs-r/.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('doubleml-py-vs-r/.github/R-version') }}-dev-pkg-test-
    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y zlib1g-dev libicu-dev pandoc make libcurl4-openssl-dev libssl-dev
    - name: Install R pkg DoubleML (dev)
      run: |
        install.packages('remotes')
        remotes::install_github("DoubleML/doubleml-for-r", dependencies = TRUE)
        remotes::install_cran("rcmdcheck")
      shell: Rscript {0}

    - name: Test with pytest
      run: |
        cd doubleml-py-vs-r
        pytest
